const KeyboardLayout = {
  russian: {
    backtick: ["ё", "Ё"],
    digit1: ["1", "!"],
    digit2: ["2", '"'],
    digit3: ["3", "№"],
    digit4: ["4", ";"],
    digit5: ["5", "%"],
    digit6: ["6", ":"],
    digit7: ["7", "?"],
    digit8: ["8", "*"],
    digit9: ["9", "("],
    digit0: ["0", ")"],
    minus: ["-", "_"],
    equal: ["=", "+"],
    backspace: ["\b"],
    keyQ: ["й", "Й"],
    keyW: ["ц", "Ц"],
    keyE: ["у", "У"],
    keyR: ["к", "К"],
    keyT: ["е", "Е"],
    keyY: ["н", "Н"],
    keyU: ["г", "Г"],
    keyI: ["ш", "Ш"],
    keyO: ["щ", "Щ"],
    keyP: ["з", "З"],
    bracketLeft: ["х", "Х"],
    bracketRight: ["ъ", "Ъ"],
    backslash: ["\\", "/"],
    capsLock: ["CapsLock"],
    keyA: ["ф", "Ф"],
    keyS: ["ы", "Ы"],
    keyD: ["в", "В"],
    keyF: ["а", "А"],
    keyG: ["п", "П"],
    keyH: ["р", "Р"],
    keyJ: ["о", "О"],
    keyK: ["л", "Л"],
    keyL: ["д", "Д"],
    semicolon: ["ж", "Ж"],
    quote: ["э", "Э"],
    
    keyZ: ["я", "Я"],
    keyX: ["ч", "Ч"],
    keyC: ["с", "С"],
    keyV: ["м", "М"],
    keyB: ["и", "И"],
    keyN: ["т", "Т"],
    keyM: ["ь", "Ь"],
    comma: [",", "<"],
    period: [".", ">"],
    slash: ["/", "?"],

    bracketLeft: ["[", "{"],
    bracketRight: ["]", "}"],
    
    tab: ["\t"],
    enter: ["\r"],
    space: [" "],
    shiftLeft: ["Shift"],
    shiftRight: ["Shift"],
    altLeft: ["Alt"],
    altRight: ["Alt"],
    controlLeft: ["Control"],
    controlRight: ["Control"],
    
    escape: ["Escape"],
    insert: ["Insert"],
    home: ["Home"],
    pageUp: ["PageUp"],
    delete: ["Delete"],
    end: ["End"],
    pageDown: ["PageDown"],
    arrowUp: ["ArrowUp"],
    arrowLeft: ["ArrowLeft"],
    arrowDown: ["ArrowDown"],
    arrowRight: ["ArrowRight"],
  },
  english: {
    backtick: ["`", "~"],
    digit1: ["1", "!"],
    digit2: ["2", "@"],
    digit3: ["3", "#"],
    digit4: ["4", "$"],
    digit5: ["5", "%"],
    digit6: ["6", "^"],
    digit7: ["7", "&"],
    digit8: ["8", "*"],
    digit9: ["9", "("],
    digit0: ["0", ")"],
    minus: ["-", "_"],
    equal: ["=", "+"],
    keyQ: ["q", "Q"],
    keyW: ["w", "W"],
    keyE: ["e", "E"],
    keyR: ["r", "R"],
    keyT: ["t", "T"],
    keyY: ["y", "Y"],
    keyU: ["u", "U"],
    keyI: ["i", "I"],
    keyO: ["o", "O"],
    keyP: ["p", "P"],
    bracketLeft: ["[", "{"],
    bracketRight: ["]", "}"],
    backslash: ["\\", "|"],
    keyA: ["a", "A"],
    keyS: ["s", "S"],
    keyD: ["d", "D"],
    keyF: ["f", "F"],
    keyG: ["g", "G"],
    keyH: ["h", "H"],
    keyJ: ["j", "J"],
    keyK: ["k", "K"],
    keyL: ["l", "L"],
    semicolon: [";", ":"],
    quote: ["'", '"'],
    keyZ: ["z", "Z"],
    keyX: ["x", "X"],
    keyC: ["c", "C"],
    keyV: ["v", "V"],
    keyB: ["b", "B"],
    keyN: ["n", "N"],
    keyM: ["m", "M"],
    comma: [",", "<"],
    period: [".", ">"],
    slash: ["/", "?"],
    backspace: ["\b"],
    tab: ["\t"],
    enter: ["\r"],
    space: [" "],
    shiftLeft: ["Shift"],
    shiftRight: ["Shift"],
    altLeft: ["Alt"],
    altRight: ["Alt"],
    controlLeft: ["Control"],
    controlRight: ["Control"],
    capsLock: ["CapsLock"],
    escape: ["Escape"],
    insert: ["Insert"],
    home: ["Home"],
    pageUp: ["PageUp"],
    delete: ["Delete"],
    end: ["End"],
    pageDown: ["PageDown"],
    arrowUp: ["ArrowUp"],
    arrowLeft: ["ArrowLeft"],
    arrowDown: ["ArrowDown"],
    arrowRight: ["ArrowRight"],
  },
};

function buildHTML() {
  document.body.className = "body";
  document.body.insertAdjacentHTML(
    "afterbegin",
    `<main class=main><h1 class="title">RSS Virtual keyboard</h1> 
     <textarea class="textarea" rows="5" cols="5"></textarea>
     <div class="keyboard"></div>
     </main>`
  );

  let keyboard = document.querySelector('keyboard');

  
}
buildHTML();
